services:
  - type: web # Serviço web para a aplicação Rails
    name: love_counter_app
    env: ruby
    buildCommand: "./bin/render-build.sh" # Script de build (veja abaixo)
    startCommand: "bundle exec pumactl start -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: love_counter_db # Nome do serviço de banco de dados abaixo
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false # Mantenha chaves secretas fora do render.yaml, configure via dashboard ou secrets files
      - key: RAILS_ENV
        value: production
      - key: RAILS_SERVE_STATIC_FILES
        value: true # Para servir assets compilados pelo Rails

  - type: pserv # Banco de dados PostgreSQL
    name: love_counter_db
    ipAllowList: [] # Permite acesso de qualquer lugar (ajuste conforme necessário para segurança)
    plan: free # Escolha o plano adequado
    databaseName: love_counter_app_production
    user: love_counter_app